Add settings for transport and repository
Kuwerin/ctf-sqli-simple pull request #15
Opened 2022-02-14 13:04 UTC by Wanderer47

2022-02-14 13:06 UTC, Kuwerin commented on src/settings.py
> +    DB_NAME: Optional[str]
Префикс db здесь лишний.

2022-02-14 13:07 UTC, Kuwerin commented on src/settings.py
> +    postgres: PostgresSettings
Лучше будет это поле обозвать `repository`

2022-02-14 13:09 UTC, Kuwerin commented on src/settings.py
> +    DB_NAME: Optional[str]
Нет дефолтных значений здесь

2022-02-14 13:10 UTC, Kuwerin commented on src/settings.py
> +from distutils.log import debug
Зачем этот импорт

2022-02-14 13:11 UTC, Kuwerin requested changes

2022-02-14 13:11 UTC, Kuwerin commented on src/settings.py
> +    DB_NAME: Optional[str]
С этими переменными сейчас сервис запускается?

2022-02-14 13:12 UTC, Wanderer47 commented on src/settings.py
> +from distutils.log import debug
Не зачем.

2022-02-14 13:14 UTC, Wanderer47 commented on src/settings.py
> +    postgres: PostgresSettings
Какое именно?

2022-02-14 13:37 UTC, Wanderer47 commented on src/settings.py
> +    DB_NAME: Optional[str]
Вроде да

2022-02-14 14:49 UTC, Kuwerin requested changes

2022-02-14 14:49 UTC, Kuwerin commented on src/settings.py
> +    NAME: Optional[str] = "postgres"
Зачем все капсом?

2022-02-14 14:50 UTC, Kuwerin commented on src/settings.py
> +    postgres: PostgresSettings
Поле `postgres` замени на `repository`. Оно одно

2022-02-14 14:58 UTC, Kuwerin requested changes

2022-02-14 14:58 UTC, Kuwerin commented on src/settings.py
> +class TransportSettings(BaseSettingsModel):
Код скопирован из примера. Длинная пустая строка. `CTRL`+`A` в коде нажми -- увидишь

2022-02-16 09:31 UTC, Kuwerin requested changes

2022-02-16 09:31 UTC, Kuwerin commented on src/repository/postgres.py
> +import re
"Приберись в коде, убери лишние импорты"

2022-02-16 10:32 UTC, Kuwerin requested changes

2022-02-16 10:32 UTC, Kuwerin commented on src/settings.py
> +    name: Optional[str] = "postgres"
Давай поле `name` переименуем в `database`, чтобы было понятно, что имеется ввиду имя базы данных. Изменить нужно в `settings.py`, `app.py`, `docker-compose.yml`

2022-02-16 14:13 UTC, merged